-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.8.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/18/2022 5:45:15 PM
-- Target server version: 8.0.30
-- Please backup your target database before running this script 

CREATE DATABASE IF NOT EXISTS AppTemplateDb COLLATE utf8mb4_0900_ai_ci;
USE AppTemplateDb;

# .\PreDeployment.sql

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
# .\Tables\permissions.sql
CREATE TABLE permissions (
  name VARCHAR(100) NOT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

# .\Tables\groups_roles.sql
CREATE TABLE groups_roles (
  name VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4;

# .\Tables\permissions_group.sql
CREATE TABLE permissions_groups (
  permission_name VARCHAR(100) NOT NULL DEFAULT '',
  group_name VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (permission_name, group_name)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

ALTER TABLE permissions_groups 
  ADD CONSTRAINT FK_permissions_groups_permissions_name FOREIGN KEY (permission_name)
    REFERENCES permissions(name);

ALTER TABLE permissions_groups 
  ADD CONSTRAINT FK_permissions_groups_groups_name FOREIGN KEY (group_name)
    REFERENCES groups_roles(name);

# .\Tables\users.sql
CREATE TABLE users (
  user_id INT NOT NULL,
  first_name VARCHAR(200) NOT NULL,
  last_nName VARCHAR(200) NOT NULL,
  email VARCHAR(500) NOT NULL,
  user_password VARCHAR(1000) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

# .\Tables\flyway_schema_history.Tables.sql
CREATE TABLE flyway_schema_history (
  installed_rank INT NOT NULL,
  version VARCHAR(50) DEFAULT NULL,
  description VARCHAR(200) NOT NULL,
  type VARCHAR(20) NOT NULL,
  script VARCHAR(1000) NOT NULL,
  checksum INT DEFAULT NULL,
  installed_by VARCHAR(100) NOT NULL,
  installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  execution_time INT NOT NULL,
  success TINYINT(1) NOT NULL,
  PRIMARY KEY (installed_rank)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

ALTER TABLE flyway_schema_history 
  ADD INDEX flyway_schema_history_s_idx(success);

# .\Tables\error_log_trace.sql
CREATE TABLE error_log_trace (
  error_lLog_traceId INT NOT NULL,
  error_log_id VARCHAR(200) NOT NULL,
  trace_message VARCHAR(200) NOT NULL,
  trace_date VARCHAR(500) NOT NULL,
  PRIMARY KEY (error_log_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

# .\Procedures\sp_Permission_Read.sql
DELIMITER $$

CREATE PROCEDURE sp_Permission_Read(
  IN permissionId int,
  OUT out_numRecords int
)
BEGIN
  SELECT COUNT(*) 
  INTO out_numRecords
  FROM Permission p;

  SELECT
    p.PermissionId,
    p.Name,
    p.Description
  FROM Permission p
  WHERE p.PermissionId = permissionId;
END
$$

DELIMITER ;


# .\PostDeployment.sql

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;